Invalid URL 'instagram.login': No schema supplied. Perhaps you meant http://instagram.login?
HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f25608a57e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff1f203b400>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa184804910>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3529039240>: Failed to establish a new connection: [Errno 111] Connection refused'))
HTTPConnectionPool(host='127.0.0.1', port=4040): Max retries exceeded with url: /api/tunnels (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f177801c9d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
